on_http_request:
  - name: Rewrite all paths to root
    expressions:
      - "req.url.path.startsWith('/')"
    actions:
      - type: url-rewrite
        config:
          from: "^/(.*)"
          to: "/"
